### ISSUE TITLE
PATCH project name

### ISSUE THREAD

**Issue by ZoeKHarvey** [N-Gibson/back-end-palette-picker#10]
PATCH:
- [x] As a user I should be able to PATCH to api/v1/projects/:id to edit an existing project
- [x] write PATCH for endpoint /api/v1/projects:id
- [x]  Body should contain: Name
 - [x] test PATCH in postman

**Comment by N-Gibson** [comment]
There is not yet a sad path test for this issue but otherwise everything is done.
