### ISSUE TITLE
PATCH palette name

### ISSUE THREAD

**Issue by ZoeKHarvey** [N-Gibson/back-end-palette-picker#11]
PATCH:
- [x] As a user I should be able to PATCH to api/v1/palettes/:id to edit an existing palette name
- [x] write PATCH for endpoint /api/v1/palettes/:id
- [x]  Body should contain: Name
 - [x] test PATCH in postman

**Comment by N-Gibson** [comment]
Again the patch has everything except one of the sad path tests.
