### ISSUE TITLE
DELETE palette

### ISSUE THREAD

**Issue by ZoeKHarvey** [N-Gibson/back-end-palette-picker#13]
DELETE:
- [x] As a user I should be able to DELETE to api/v1/palettes/:id to remove an existing palette
- [x] write DELETE for endpoint /api/v1/palettes/:id
 - [x] test DELETE in postman

**Comment by N-Gibson** [comment]
Tests are working properly as well as the deleting functionality for the endpoint: /api/v1/palettes/:id
